apiVersion: v1
kind: Service
metadata:
  name: {{ include "jmeter-next.controller.fullname" . }}
  labels:
    {{- include "jmeter-next.controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    - port: {{ .Values.controller.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.controller.service.uiPort }}
      targetPort: ui
      protocol: TCP
      name: ui
  selector:
    {{- include "jmeter-next.controller.selectorLabels" . | nindent 4 }}
