apiVersion: v1
kind: Service
metadata:
  name: {{ include "jmeter-next.worker.headlessServiceName" . }}
  labels:
    {{- include "jmeter-next.worker.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.worker.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.worker.healthPort }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "jmeter-next.worker.selectorLabels" . | nindent 4 }}
