/**
 * Worker-proto: generated gRPC stub classes and protobuf message types.
 *
 * <p>The Java sources in this package are generated by the protobuf Gradle plugin
 * from the {@code .proto} files in {@code src/main/proto/}. Do not edit
 * generated files by hand.
 */
package com.b3meter.worker.proto;
